export { default as DataClinic } from './DataClinic'
export { default as ResponsibleTecnic } from './ResponsibleTecnic'
export { default as ResponsibleAdministrative } from './ResponsibleAdministrative'
export { default as Address } from './Address'
export { default as Specialtys } from './Specialtys'
