export const columnsOptions = [
  { id: 'all', name: 'Todas' },
  { id: 'id', name: 'ID' },
  { id: 'beneficiaryType', name: 'Tipo de Beneficiário' },
  { id: 'contractNumber', name: 'Nº do contrato' },
  { id: 'name', name: 'Nome' },
  { id: 'cpf', name: 'CPF' },
  { id: 'birthDate', name: 'Data de Nascimento' },
  { id: 'email', name: 'E-mail' },
  { id: 'gender', name: 'Sexo' },
  { id: 'plan', name: 'Plano' },
  { id: 'table', name: 'Tabela' },
  { id: 'phone', name: 'Celular' },
  { id: 'address', name: 'Logradouro' },
  { id: 'number', name: 'Numero' },
  { id: 'complement', name: 'Complemento' },
  { id: 'district', name: 'Bairro' },
  { id: 'city', name: 'Cidade' },
  { id: 'uf', name: 'UF' },
  { id: 'cep', name: 'CEP' },
  { id: 'status', name: 'Status' },
  { id: 'registerDate', name: 'Data de Cadastro' },
  { id: 'exclusionDate', name: 'Data de Exclusão' },
  { id: 'validationDate', name: 'Data de Validação' },
]
