image: 'atlassian/default-image:2'
pipelines:
  default:
    - step:
        script:
          - echo "Host git-codecommit.*.amazonaws.com" >> ~/.ssh/config
          - echo "User $SSHKEY" >> ~/.ssh/config
          - git remote add codecommit $URL
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git fetch codecommit development; fi;
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git pull  codecommit development; fi;
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git push  codecommit master:development; fi;