image: 'atlassian/default-image:2'
definitions: 
  steps:
    - step: &codecommit_mirror
        name: Default mirror
        script:
          - echo "Host git-codecommit.*.amazonaws.com" >> ~/.ssh/config
          - echo "User $SSHKEY" >> ~/.ssh/config
          - git remote add codecommit $URL
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git fsck --full; fi;
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git fetch --unshallow codecommit development; fi;
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git pull  codecommit development; fi;
          - if [[ $BITBUCKET_BRANCH == 'master' ]]; then git push  codecommit master:development --follow-tags; fi;

pipelines:
  default:
    - step: *codecommit_mirror
  tags:
    '*':
      - step: 
          <<: *codecommit_mirror
          name: Tag mirror