image: 'atlassian/default-image:2'
definitions: 
  steps:
    - step: &codecommit_mirror
        name: Default mirror
        script:
          - npm i --save-dev @types/node
          - npm install typescript ts-node
          - npm install -D tslib @types/node
          - npx --experimental-modules ts-node ./src/updateVersion.ts ${BITBUCKET_BUILD_NUMBER}
          - git add .
          - git commit -m "Versão atualizada [skip ci]"
          - git push
          - echo "Host git-codecommit.*.amazonaws.com" >> ~/.ssh/config
          - echo "User $SSHKEY" >> ~/.ssh/config
          - git remote add codecommit $URL
          - git fsck --full
          - git fetch --unshallow codecommit development
          - git pull codecommit development
          - git push codecommit master:development --follow-tags

pipelines:
  branches:
    master:
      - step: *codecommit_mirror
  tags:
    v*:
      - step: 
          <<: *codecommit_mirror
          name: Tag mirror