export const typesResponses = {
  PASSWORD_CHANGED_SUCCESSFULLY: 'PASSWORD CHANGED SUCCESSFULLY',
  SAME_PASSWORD_AS_OLD: 'SAME_PASSWORD_AS_OLD',
  INCORRECT_PASSWORD: 'INCORRECT_PASSWORD',
  FRONTEND_COULD_NOT_HANDLE_ERROR: 'FRONTEND_COULD_NOT_HANDLE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
}
