export const typesResponses = {
  CPF_NOT_FOUND: 'CPF_NOT_FOUND',
  CPF_IS_ACTIVE: 'CPF_IS_ACTIVE',
  CPF_IS_INACTIVE_OR_DENIED: 'CPF_IS_INACTIVE_OR_DENIED',
  CPF_IS_PENDING_OR_WAITING: 'CPF_IS_PENDING_OR_WAITING',
  FRONTEND_COULD_NOT_HANDLE_ERROR: 'FRONTEND_COULD_NOT_HANDLE_ERROR',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
}
