export const UF = [
  { label: 'Acre', value: 1 },
  { label: 'Alagoas', value: 2 },
  { label: 'Amapá', value: 3 },
  { label: 'Amazonas', value: 4 },
  { label: 'Bahia', value: 5 },
  { label: 'Ceará', value: 7 },
  { label: 'Distrito Federal', value: 9 },
  { label: 'Espírito Santo', value: 10 },
  { label: 'Goías', value: 11 },
  { label: 'Maranhão', value: 12 },
  { label: 'Mato Grosso', value: 15 },
  { label: 'Mato Grosso do Sul', value: 14 },
  { label: 'Minas Gerais', value: 13 },
  { label: 'Pará', value: 16 },
  { label: 'Paraíba', value: 17 },
  { label: 'Paraná', value: 20 },
  { label: 'Pernambuco', value: 18 },
  { label: 'Piauí', value: 19 },
  { label: 'Rio de Janeiro', value: 21 },
  { label: 'Rio Grande do Norte', value: 22 },
  { label: 'Rio Grande do Sul', value: 25 },
  { label: 'Rondônia', value: 23 },
  { label: 'Roraíma', value: 24 },
  { label: 'Santa Catarina', value: 26 },
  { label: 'São Paulo', value: 28 },
  { label: 'Sergipe', value: 27 },
  { label: 'Tocantins', value: 29 },
]
