export const permissionList = {
  VER_MEUS_DADOS_PACIENTE: 'VER_MEUS_DADOS_PACIENTE',
  LISTAR_PACIENTES_VALIDACAO: 'LISTAR_PACIENTES_VALIDACAO',
  PERMITIR_TODOS_STATUS_PACIENTE: 'PERMITIR_TODOS_STATUS_PACIENTE',
  VER_MEUS_DEPENDENTES: 'VER_MEUS_DEPENDENTES',
  TROCAR_MINHA_SENHA: 'TROCAR_MINHA_SENHA',
  LISTAR_LOG_VALIDACOES: 'LISTAR_LOG_VALIDACOES',
  VER_ELEGIBILIDADE_PACIENTE: 'VER_ELEGIBILIDADE_PACIENTE',
  LISTAR_PLANO_DIRETOR: 'LISTAR_PLANO_DIRETOR',
  LISTAR_ITENS_VENDAVEIS: 'LISTAR_ITENS_VENDAVEIS',
  LISTAR_CLINICAS: 'LISTAR_CLINICAS',
  ALTERAR_DADOS_PACIENTE: 'ALTERAR_DADOS_PACIENTE',
}
